language: python

python:
  - "3.6"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux32.tar.gz
  - tar -xvzf geckodriver-v0.24.0-linux32.tar.gz
  - chmod +x geckodriver
  - mkdir -p $PWD/geckodriver && mv geckodriver $PWD/geckodriver
  - export PATH="$PWD/geckodriver:$PATH"

install:
  - pip install -r requirements.txt

script:
  - echo $PATH && ls -al $PWD/geckodriver && geckodriver --version && python manage.py test
