version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=django
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=db
  web:
    build: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
