# Generated by Django 3.0.3 on 2020-02-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='chunk_size',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='domain',
            name='passwords_dict',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='domain',
            name='usernames_dict',
            field=models.CharField(default='', max_length=200),
        ),
    ]
