# Generated by Django 3.0.3 on 2020-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200213_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='url',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
