# Generated by Django 3.0.3 on 2020-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200224_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_agent',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
