# Generated by Django 3.0.3 on 2020-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200218_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='password_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='username_offset',
            field=models.IntegerField(default=0),
        ),
    ]
