# Generated by Django 3.0.3 on 2020-02-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200220_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('user_agent', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'password'), (0, 'username')])),
                ('ack', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Client')),
            ],
        ),
    ]
