# Generated by Django 3.0.3 on 2020-02-20 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200220_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Domain'),
        ),
        migrations.AddField(
            model_name='offset',
            name='last_send',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
