# Generated by Django 3.0.3 on 2020-02-21 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200220_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='online',
        ),
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
