# Generated by Django 3.0.3 on 2020-02-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200221_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offset',
            name='client',
        ),
        migrations.RemoveField(
            model_name='offset',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='current_offset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Offset'),
        ),
        migrations.AlterField(
            model_name='offset',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Domain'),
        ),
    ]
